In [2]:
!pip install tensorflow

     ---------------------------------------- 0.0/48.6 kB ? eta -:--:--
     ---------------------------------------- 48.6/48.6 kB ? eta 0:00:00
   ---------------------------------------- 0.0/390.3 MB ? eta -:--:--
   ---------------------------------------- 0.7/390.3 MB 13.9 MB/s eta 0:00:28
   ---------------------------------------- 1.4/390.3 MB 14.5 MB/s eta 0:00:27
   ---------------------------------------- 2.2/390.3 MB 15.3 MB/s eta 0:00:26
   ---------------------------------------- 2.9/390.3 MB 15.5 MB/s eta 0:00:26
   ---------------------------------------- 3.7/390.3 MB 15.6 MB/s eta 0:00:25
   ---------------------------------------- 4.5/390.3 MB 15.8 MB/s eta 0:00:25
   ---------------------------------------- 4.7/390.3 MB 15.8 MB/s eta 0:00:25
    --------------------------------------- 4.9/390.3 MB 13.1 MB/s eta 0:00:30
    --------------------------------------- 5.6/390.3 MB 13.3 MB/s eta 0:00:29
    --------------------------------------- 6.4/390.3 MB 13.6 MB/s eta 0:

In [3]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

c:\Users\danie\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.00809725, -0.02887758,  0.35105363,  0.39680165,  0.42420885,
         1.0093361 ,  0.31433666,  0.36918077, -0.2769025 ,  0.13866968]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.07262024, 0.06998414, 0.10232969, 0.10711981, 0.11009625,
        0.19764696, 0.09864061, 0.10420156, 0.05461146, 0.08274932]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

1.6212729

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8585 - loss: 0.4868
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9569 - loss: 0.1501
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9664 - loss: 0.1089
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9733 - loss: 0.0847
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9766 - loss: 0.0735


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 2ms/step - accuracy: 0.9780 - loss: 0.0719


[0.07186615467071533, 0.9779999852180481]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.6164246e-07, 1.8407642e-08, 5.6860636e-06, 1.1653216e-04,
        2.2655622e-11, 3.7184088e-07, 6.9907208e-14, 9.9984670e-01,
        2.6597237e-07, 3.0009245e-05],
       [2.5560311e-07, 2.1728192e-04, 9.9976534e-01, 1.3907800e-05,
        2.2924441e-15, 3.1500990e-06, 5.4591855e-08, 2.9851681e-12,
        7.8304005e-08, 1.0668676e-13],
       [2.3579393e-07, 9.9965930e-01, 4.9012247e-05, 6.3700935e-07,
        3.7786642e-05, 3.9241468e-06, 5.1131461e-05, 1.6901884e-04,
        2.8398596e-05, 4.5997146e-07],
       [9.9973673e-01, 2.5571914e-11, 3.1998756e-05, 9.5984136e-09,
        5.3519750e-07, 1.8313123e-04, 9.4636143e-06, 5.3720606e-07,
        2.2994850e-08, 3.7614034e-05],
       [2.6963411e-05, 3.4259685e-11, 8.1690278e-06, 1.3638841e-08,
        9.9679679e-01, 5.9606114e-06, 8.9459063e-06, 5.8513215e-05,
        4.2583639e-07, 3.0943470e-03]], dtype=float32)>